trigger:
- master
- test


jobs:
- job: Main
  timeoutInMinutes: 0
  strategy:
    matrix:
      mac39:
        imageName: 'macos-10.15'
        python.version: '3.9'
      windows39:
        imageName: 'windows-2019'
        python.version: '3.9'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install numpy
      pip install scipy
      pip install packaging
    displayName: 'Install dependencies'

  - script: |
      pip install -ve .
    displayName: 'build'

  - script: |
      pip install pytest
      pip install pytest-cov
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=igl --cov-report=xml --cov-report=html
    displayName: 'testing'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
